# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Kevins Sonarcloud'
    organization: 'zero-width-whitespace'
    scannerMode: 'MSBuild'
    projectKey: 'Zero-Width-Whitespace_zero-width-docker-api'

- task: NuGetToolInstaller@1
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    restoreNugetPackages: true

- task: SonarCloudAnalyze@1

- task: Docker@2
  name: 'Docker_Build_and_Publish'
  inputs:
    containerRegistry: 'Docker'
    repository: 'MinorRepository'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'